name: CI

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Install Playwright (browsers + deps)
        run: npx playwright install --with-deps

      # Playwright will start servers per playwright.config.ts:webServer
      - name: Run Playwright tests
        env:
          APP_URL: http://localhost:3000
        run: npm run test:ci

      - name: Upload Playwright HTML report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
