name: CI

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (lockfile enforced)
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Run E2E (boot backend+Next and test)
        env:
          CI: true
        run: npm run ci:e2e
