name: CI

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      APP_URL: ${{ secrets.APP_URL || 'http://localhost:3000' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # If you ever host a preview URL, set APP_URL secret and skip the dev server.
      # Otherwise, you can start a local app here if available in this repo.
      # For now we just run tests which assume APP_URL points to a running app.

      - name: Run tests
        run: npm run test:ci
